name: Pre-release

on:
  push:
    branches:
      - features/burai-zenin
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    name: Pre-release for DOA2U Burai Zenin Fix
    if: github.repository_owner == 'MattPonton'
    uses: ./.github/workflows/release.yml
    with:
      ref: ${{ github.sha }}
      tag: doa-pre-release
      pre-release: true
